name: chemdash

channels:
  - openbabel
#  - rpmuller
  - pyscf
  - psi4
  - rdkit

dependencies:
  - python=3
  - pip
  - jupyter
  - nb_conda
  - ipykernel 
  - psutil
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - openbabel
  - rdkit
# - cirpy
# - pyquante2
  - pyscf
  - psi4
  - pip:
    - py3Dmol
    - ase
    - torch
    - torchvision
    - torchani
    

